### ISSUE TITLE
Right trigger inputs overwrite any other input source with the same action attached.

### ISSUE THREAD

**Issue by federbenjamin** [canadianbif/Symbiosis#10]
On the controller i have, pressing the right trigger will shut off input signals from all 3 other augment swap request buttons (left trigger, 1, and 2).

**Comment by Grochoci** [comment]
Currently it has been identified that the triggers are overriding their respective inputs.
I added two different variables for triggerRight and triggerLeft so they act independently of each other.

This however still overwrites their keyboard inputs under the same name. Something weird is happening.

For now keyboard inputs will not work if the trigger disables them. SHOULD be good to keep going from here since controllers will be the primary input device.

**Comment by federbenjamin** [comment]
So can i close this?
